// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type DefaultPageDocumentDataSlicesSlice =
  | ProductSlice
  | ProductsSlice
  | PerksSlice
  | PageTitleSlice
  | ParallaxImageGridSlice
  | ContactFormSlice
  | ImageAndTextSlice
  | DividerSlice
  | HeroSlice
  | TitleAndTextSlice;

/**
 * Content for Default Page documents
 */
interface DefaultPageDocumentData {
  /**
   * SEO Title field in *Default Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: default_page.seo_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  seo_title: prismic.KeyTextField;

  /**
   * SEO Description field in *Default Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: default_page.seo_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  seo_description: prismic.KeyTextField;

  /**
   * Slice Zone field in *Default Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: default_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<DefaultPageDocumentDataSlicesSlice>;
}

/**
 * Default Page document from Prismic
 *
 * - **API ID**: `default_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type DefaultPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<DefaultPageDocumentData>,
    "default_page",
    Lang
  >;

/**
 * Item in *Footer → Links*
 */
export interface FooterDocumentDataLinksItem {
  /**
   * Title field in *Footer → Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.links[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Link field in *Footer → Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Item in *Footer → Social*
 */
export interface FooterDocumentDataSocialItem {
  /**
   * Title field in *Footer → Social*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.social[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Link field in *Footer → Social*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.social[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Icon field in *Footer → Social*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.social[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;
}

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * Links field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  links: prismic.GroupField<Simplify<FooterDocumentDataLinksItem>>;

  /**
   * Social field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.social[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  social: prismic.GroupField<Simplify<FooterDocumentDataSocialItem>>;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

type HomePageDocumentDataSlicesSlice =
  | PageTitleSlice
  | PerksSlice
  | ContactFormSlice
  | ParallaxImageGridSlice
  | DividerSlice
  | ImageAndTextSlice
  | TitleAndTextSlice
  | HeroSlice;

/**
 * Content for Home Page documents
 */
interface HomePageDocumentData {
  /**
   * SEO Title field in *Home Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.seo_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  seo_title: prismic.KeyTextField;

  /**
   * SEO Description field in *Home Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.seo_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  seo_description: prismic.KeyTextField;

  /**
   * Slice Zone field in *Home Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomePageDocumentDataSlicesSlice>;
}

/**
 * Home Page document from Prismic
 *
 * - **API ID**: `home_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomePageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<HomePageDocumentData>,
    "home_page",
    Lang
  >;

/**
 * Item in *Menu → Menu link*
 */
export interface MenuDocumentDataMenuLinkItem {
  /**
   * Title field in *Menu → Menu link*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.menu_link[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Link field in *Menu → Menu link*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.menu_link[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

type MenuDocumentDataSlicesSlice = never;

/**
 * Content for Menu documents
 */
interface MenuDocumentData {
  /**
   * Menu link field in *Menu*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.menu_link[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  menu_link: prismic.GroupField<Simplify<MenuDocumentDataMenuLinkItem>>;

  /**
   * `slices` field in *Menu*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<MenuDocumentDataSlicesSlice>;
}

/**
 * Menu document from Prismic
 *
 * - **API ID**: `menu`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MenuDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<MenuDocumentData>, "menu", Lang>;

/**
 * Item in *Product → Images*
 */
export interface ProductDocumentDataImagesItem {
  /**
   * Image field in *Product → Images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: product.images[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Item in *Product → Specs*
 */
export interface ProductDocumentDataSpecsItem {
  /**
   * Title field in *Product → Specs*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product.specs[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Value field in *Product → Specs*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product.specs[].value
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  value: prismic.KeyTextField;
}

/**
 * Content for Product documents
 */
interface ProductDocumentData {
  /**
   * Title field in *Product*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Product*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Images field in *Product*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: product.images[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  images: prismic.GroupField<Simplify<ProductDocumentDataImagesItem>>;

  /**
   * Price field in *Product*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product.price
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  price: prismic.KeyTextField;

  /**
   * Specs field in *Product*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: product.specs[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  specs: prismic.GroupField<Simplify<ProductDocumentDataSpecsItem>>;
}

/**
 * Product document from Prismic
 *
 * - **API ID**: `product`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProductDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProductDocumentData>,
    "product",
    Lang
  >;

type ProductPageDocumentDataSlicesSlice = ProductSlice;

/**
 * Content for Product Page documents
 */
interface ProductPageDocumentData {
  /**
   * SEO Title field in *Product Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product_page.seo_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  seo_title: prismic.KeyTextField;

  /**
   * SEO Description field in *Product Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product_page.seo_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  seo_description: prismic.KeyTextField;

  /**
   * Slice Zone field in *Product Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: product_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ProductPageDocumentDataSlicesSlice>;
}

/**
 * Product Page document from Prismic
 *
 * - **API ID**: `product_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProductPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProductPageDocumentData>,
    "product_page",
    Lang
  >;

/**
 * Item in *Products page → Products*
 */
export interface ProductsPageDocumentDataProductsItem {
  /**
   * Products field in *Products page → Products*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: products_page.products[].products
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  products: prismic.ContentRelationshipField<"product">;
}

/**
 * Content for Products page documents
 */
interface ProductsPageDocumentData {
  /**
   * SEO Title field in *Products page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: products_page.seo_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  seo_title: prismic.KeyTextField;

  /**
   * SEO Description field in *Products page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: products_page.seo_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  seo_description: prismic.KeyTextField;

  /**
   * Products field in *Products page*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: products_page.products[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  products: prismic.GroupField<Simplify<ProductsPageDocumentDataProductsItem>>;
}

/**
 * Products page document from Prismic
 *
 * - **API ID**: `products_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProductsPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProductsPageDocumentData>,
    "products_page",
    Lang
  >;

export type AllDocumentTypes =
  | DefaultPageDocument
  | FooterDocument
  | HomePageDocument
  | MenuDocument
  | ProductDocument
  | ProductPageDocument
  | ProductsPageDocument;

/**
 * Primary content in *ContactForm → Default → Primary*
 */
export interface ContactFormSliceDefaultPrimary {
  /**
   * Title field in *ContactForm → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *ContactForm → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for ContactForm Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactFormSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactFormSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContactForm*
 */
type ContactFormSliceVariation = ContactFormSliceDefault;

/**
 * ContactForm Shared Slice
 *
 * - **API ID**: `contact_form`
 * - **Description**: ContactForm
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactFormSlice = prismic.SharedSlice<
  "contact_form",
  ContactFormSliceVariation
>;

/**
 * Default variation for Divider Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DividerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Divider*
 */
type DividerSliceVariation = DividerSliceDefault;

/**
 * Divider Shared Slice
 *
 * - **API ID**: `divider`
 * - **Description**: Divider
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DividerSlice = prismic.SharedSlice<
  "divider",
  DividerSliceVariation
>;

/**
 * Item in *Hero → Default → Primary → Hero CTA*
 */
export interface HeroSliceDefaultPrimaryHeroCtaItem {
  /**
   * Title field in *Hero → Default → Primary → Hero CTA*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.hero_cta[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Link field in *Hero → Default → Primary → Hero CTA*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.hero_cta[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Hero Image field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.hero_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  hero_image: prismic.ImageField<never>;

  /**
   * Flip Words field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.flip_words
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  flip_words: prismic.KeyTextField;

  /**
   * Hero Text field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.hero_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  hero_text: prismic.RichTextField;

  /**
   * Hero CTA field in *Hero → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.hero_cta[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  hero_cta: prismic.GroupField<Simplify<HeroSliceDefaultPrimaryHeroCtaItem>>;

  /**
   * Hero description field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.hero_description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  hero_description: prismic.KeyTextField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Item in *ImageAndText → Default → Primary → CTAs*
 */
export interface ImageAndTextSliceDefaultPrimaryCtasItem {
  /**
   * Title field in *ImageAndText → Default → Primary → CTAs*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_and_text.default.primary.ctas[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Link field in *ImageAndText → Default → Primary → CTAs*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: image_and_text.default.primary.ctas[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Item in *ImageAndText → Reverse → Primary → CTAs*
 */
export interface ImageAndTextSliceReversePrimaryCtasItem {
  /**
   * Title field in *ImageAndText → Reverse → Primary → CTAs*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_and_text.reverse.primary.ctas[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Link field in *ImageAndText → Reverse → Primary → CTAs*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: image_and_text.reverse.primary.ctas[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Primary content in *ImageAndText → Default → Primary*
 */
export interface ImageAndTextSliceDefaultPrimary {
  /**
   * Image field in *ImageAndText → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_and_text.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *ImageAndText → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_and_text.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Text field in *ImageAndText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_and_text.default.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * CTAs field in *ImageAndText → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: image_and_text.default.primary.ctas[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  ctas: prismic.GroupField<Simplify<ImageAndTextSliceDefaultPrimaryCtasItem>>;

  /**
   * CTA Group field in *ImageAndText → Default → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: image_and_text.default.primary.cta_group
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_group: prismic.ContentRelationshipField<"cta_group">;
}

/**
 * Default variation for ImageAndText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageAndTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageAndTextSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *ImageAndText → Reverse → Primary*
 */
export interface ImageAndTextSliceReversePrimary {
  /**
   * Image field in *ImageAndText → Reverse → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_and_text.reverse.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *ImageAndText → Reverse → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_and_text.reverse.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Text field in *ImageAndText → Reverse → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_and_text.reverse.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * CTAs field in *ImageAndText → Reverse → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: image_and_text.reverse.primary.ctas[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  ctas: prismic.GroupField<Simplify<ImageAndTextSliceReversePrimaryCtasItem>>;
}

/**
 * Reverse variation for ImageAndText Slice
 *
 * - **API ID**: `reverse`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageAndTextSliceReverse = prismic.SharedSliceVariation<
  "reverse",
  Simplify<ImageAndTextSliceReversePrimary>,
  never
>;

/**
 * Slice variation for *ImageAndText*
 */
type ImageAndTextSliceVariation =
  | ImageAndTextSliceDefault
  | ImageAndTextSliceReverse;

/**
 * ImageAndText Shared Slice
 *
 * - **API ID**: `image_and_text`
 * - **Description**: ImageAndText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageAndTextSlice = prismic.SharedSlice<
  "image_and_text",
  ImageAndTextSliceVariation
>;

/**
 * Primary content in *PageTitle → Default → Primary*
 */
export interface PageTitleSliceDefaultPrimary {
  /**
   * Title field in *PageTitle → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page_title.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Sub Title field in *PageTitle → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page_title.default.primary.sub_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sub_title: prismic.KeyTextField;
}

/**
 * Default variation for PageTitle Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PageTitleSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PageTitleSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PageTitle*
 */
type PageTitleSliceVariation = PageTitleSliceDefault;

/**
 * PageTitle Shared Slice
 *
 * - **API ID**: `page_title`
 * - **Description**: PageTitle
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PageTitleSlice = prismic.SharedSlice<
  "page_title",
  PageTitleSliceVariation
>;

/**
 * Item in *ParallaxImageGrid → Default → Primary → Images*
 */
export interface ParallaxImageGridSliceDefaultPrimaryImagesItem {
  /**
   * Link field in *ParallaxImageGrid → Default → Primary → Images*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: parallax_image_grid.default.primary.images[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Primary content in *ParallaxImageGrid → Default → Primary*
 */
export interface ParallaxImageGridSliceDefaultPrimary {
  /**
   * Title field in *ParallaxImageGrid → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: parallax_image_grid.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Images field in *ParallaxImageGrid → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: parallax_image_grid.default.primary.images[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  images: prismic.GroupField<
    Simplify<ParallaxImageGridSliceDefaultPrimaryImagesItem>
  >;
}

/**
 * Default variation for ParallaxImageGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ParallaxImageGridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ParallaxImageGridSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ParallaxImageGrid*
 */
type ParallaxImageGridSliceVariation = ParallaxImageGridSliceDefault;

/**
 * ParallaxImageGrid Shared Slice
 *
 * - **API ID**: `parallax_image_grid`
 * - **Description**: ParallaxImageGrid
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ParallaxImageGridSlice = prismic.SharedSlice<
  "parallax_image_grid",
  ParallaxImageGridSliceVariation
>;

/**
 * Item in *Perks → Default → Primary → Perk*
 */
export interface PerksSliceDefaultPrimaryPerkItem {
  /**
   * Title field in *Perks → Default → Primary → Perk*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: perks.default.primary.perk[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Perks → Default → Primary → Perk*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: perks.default.primary.perk[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Icon field in *Perks → Default → Primary → Perk*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: perks.default.primary.perk[].icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icon: prismic.ImageField<never>;
}

/**
 * Primary content in *Perks → Default → Primary*
 */
export interface PerksSliceDefaultPrimary {
  /**
   * Title field in *Perks → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: perks.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Perk field in *Perks → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: perks.default.primary.perk[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  perk: prismic.GroupField<Simplify<PerksSliceDefaultPrimaryPerkItem>>;
}

/**
 * Default variation for Perks Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PerksSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PerksSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Perks*
 */
type PerksSliceVariation = PerksSliceDefault;

/**
 * Perks Shared Slice
 *
 * - **API ID**: `perks`
 * - **Description**: Perks
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PerksSlice = prismic.SharedSlice<"perks", PerksSliceVariation>;

/**
 * Item in *Product → Default → Primary → Image*
 */
export interface ProductSliceDefaultPrimaryImageItem {
  /**
   * Image field in *Product → Default → Primary → Image*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: product.default.primary.image[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Item in *Product → Default → Primary → Features*
 */
export interface ProductSliceDefaultPrimaryFeaturesItem {
  /**
   * Title field in *Product → Default → Primary → Features*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product.default.primary.features[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Value field in *Product → Default → Primary → Features*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product.default.primary.features[].value
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  value: prismic.KeyTextField;
}

/**
 * Primary content in *Product → Default → Primary*
 */
export interface ProductSliceDefaultPrimary {
  /**
   * Title field in *Product → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Product → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Image field in *Product → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: product.default.primary.image[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  image: prismic.GroupField<Simplify<ProductSliceDefaultPrimaryImageItem>>;

  /**
   * Features field in *Product → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: product.default.primary.features[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  features: prismic.GroupField<
    Simplify<ProductSliceDefaultPrimaryFeaturesItem>
  >;
}

/**
 * Default variation for Product Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProductSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProductSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Product*
 */
type ProductSliceVariation = ProductSliceDefault;

/**
 * Product Shared Slice
 *
 * - **API ID**: `product`
 * - **Description**: Product
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProductSlice = prismic.SharedSlice<
  "product",
  ProductSliceVariation
>;

/**
 * Item in *Products → Default → Primary → Products*
 */
export interface ProductsSliceDefaultPrimaryProductsItem {
  /**
   * Product field in *Products → Default → Primary → Products*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: products.default.primary.products[].product
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  product: prismic.ContentRelationshipField<"product_page">;
}

/**
 * Primary content in *Products → Default → Primary*
 */
export interface ProductsSliceDefaultPrimary {
  /**
   * Title field in *Products → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: products.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Products field in *Products → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: products.default.primary.products[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  products: prismic.GroupField<
    Simplify<ProductsSliceDefaultPrimaryProductsItem>
  >;
}

/**
 * Default variation for Products Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProductsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProductsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Products*
 */
type ProductsSliceVariation = ProductsSliceDefault;

/**
 * Products Shared Slice
 *
 * - **API ID**: `products`
 * - **Description**: Products
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProductsSlice = prismic.SharedSlice<
  "products",
  ProductsSliceVariation
>;

/**
 * Item in *TitleAndText → Default → Primary → CTA*
 */
export interface TitleAndTextSliceDefaultPrimaryCtaItem {
  /**
   * Title field in *TitleAndText → Default → Primary → CTA*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: title_and_text.default.primary.cta[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Link field in *TitleAndText → Default → Primary → CTA*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: title_and_text.default.primary.cta[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Primary content in *TitleAndText → Default → Primary*
 */
export interface TitleAndTextSliceDefaultPrimary {
  /**
   * Title field in *TitleAndText → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: title_and_text.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Category field in *TitleAndText → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: title_and_text.default.primary.category
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  category: prismic.KeyTextField;

  /**
   * Section Text field in *TitleAndText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: title_and_text.default.primary.section_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  section_text: prismic.RichTextField;

  /**
   * CTA field in *TitleAndText → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: title_and_text.default.primary.cta[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  cta: prismic.GroupField<Simplify<TitleAndTextSliceDefaultPrimaryCtaItem>>;
}

/**
 * Default variation for TitleAndText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleAndTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TitleAndTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TitleAndText*
 */
type TitleAndTextSliceVariation = TitleAndTextSliceDefault;

/**
 * TitleAndText Shared Slice
 *
 * - **API ID**: `title_and_text`
 * - **Description**: TitleAndText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleAndTextSlice = prismic.SharedSlice<
  "title_and_text",
  TitleAndTextSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      DefaultPageDocument,
      DefaultPageDocumentData,
      DefaultPageDocumentDataSlicesSlice,
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataLinksItem,
      FooterDocumentDataSocialItem,
      HomePageDocument,
      HomePageDocumentData,
      HomePageDocumentDataSlicesSlice,
      MenuDocument,
      MenuDocumentData,
      MenuDocumentDataMenuLinkItem,
      MenuDocumentDataSlicesSlice,
      ProductDocument,
      ProductDocumentData,
      ProductDocumentDataImagesItem,
      ProductDocumentDataSpecsItem,
      ProductPageDocument,
      ProductPageDocumentData,
      ProductPageDocumentDataSlicesSlice,
      ProductsPageDocument,
      ProductsPageDocumentData,
      ProductsPageDocumentDataProductsItem,
      AllDocumentTypes,
      ContactFormSlice,
      ContactFormSliceDefaultPrimary,
      ContactFormSliceVariation,
      ContactFormSliceDefault,
      DividerSlice,
      DividerSliceVariation,
      DividerSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimaryHeroCtaItem,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      ImageAndTextSlice,
      ImageAndTextSliceDefaultPrimaryCtasItem,
      ImageAndTextSliceDefaultPrimary,
      ImageAndTextSliceReversePrimaryCtasItem,
      ImageAndTextSliceReversePrimary,
      ImageAndTextSliceVariation,
      ImageAndTextSliceDefault,
      ImageAndTextSliceReverse,
      PageTitleSlice,
      PageTitleSliceDefaultPrimary,
      PageTitleSliceVariation,
      PageTitleSliceDefault,
      ParallaxImageGridSlice,
      ParallaxImageGridSliceDefaultPrimaryImagesItem,
      ParallaxImageGridSliceDefaultPrimary,
      ParallaxImageGridSliceVariation,
      ParallaxImageGridSliceDefault,
      PerksSlice,
      PerksSliceDefaultPrimaryPerkItem,
      PerksSliceDefaultPrimary,
      PerksSliceVariation,
      PerksSliceDefault,
      ProductSlice,
      ProductSliceDefaultPrimaryImageItem,
      ProductSliceDefaultPrimaryFeaturesItem,
      ProductSliceDefaultPrimary,
      ProductSliceVariation,
      ProductSliceDefault,
      ProductsSlice,
      ProductsSliceDefaultPrimaryProductsItem,
      ProductsSliceDefaultPrimary,
      ProductsSliceVariation,
      ProductsSliceDefault,
      TitleAndTextSlice,
      TitleAndTextSliceDefaultPrimaryCtaItem,
      TitleAndTextSliceDefaultPrimary,
      TitleAndTextSliceVariation,
      TitleAndTextSliceDefault,
    };
  }
}
