import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/Header";
import { Poppins } from "next/font/google";
import classNames from "classnames";
import { PrismicPreview } from "@prismicio/next";
import config from "../../slicemachine.config.json";
import { createClient } from "@/prismicio";
import Footer from "./components/layout/Footer";

const poppins = Poppins({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  variable: "--poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const client = createClient();
  const request = await client.getByType("menu");
  const menuItems = request.results[0].data.menu_link;
  return (
    <html lang="en" className="dark">
      <head>
        <script
          async
          defer
          src="https://static.cdn.prismic.io/prismic.js?new=true&repo=dlgutars"
        ></script>
      </head>
      <body className={classNames(poppins.variable, "bg-black")}>
        <div className="font-poppins font-thin">
          <Header menuItems={menuItems} />
          <div className="h-[90px]"></div>
          {children}
          <Footer />
        </div>
        <PrismicPreview repositoryName={config.repositoryName} />
      </body>
    </html>
  );
}
