// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  contact_form: dynamic(() => import("./ContactForm")),
  divider: dynamic(() => import("./Divider")),
  hero: dynamic(() => import("./Hero")),
  image_and_text: dynamic(() => import("./ImageAndText")),
  parallax_image_grid: dynamic(() => import("./ParallaxImageGrid")),
  title_and_text: dynamic(() => import("./TitleAndText")),
};
