// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  contact_form: dynamic(() => import("./ContactForm")),
  divider: dynamic(() => import("./Divider")),
  hero: dynamic(() => import("./Hero")),
  image_and_text: dynamic(() => import("./ImageAndText")),
  page_title: dynamic(() => import("./PageTitle")),
  parallax_image_grid: dynamic(() => import("./ParallaxImageGrid")),
  perks: dynamic(() => import("./Perks")),
  product: dynamic(() => import("./Product")),
  products: dynamic(() => import("./Products")),
  title_and_text: dynamic(() => import("./TitleAndText")),
};
